import { expect, test } from "@playwright/test";

import { APP_SETTINGS } from "./support/tauri-fixtures";
import {
  emitTauriEvent,
  installEventProbe,
  listenerCounts,
} from "./support/tauri-event-probe";
import { installTauriMock } from "./support/tauri-mock";

/* The route owns eight HUD subscriptions. The appearance and theme follows are
 * separate route/bootstrap subscriptions and stay in this receipt too. */
const OVERLAY_LISTENERS = {
  "show-overlay": 1,
  "hide-overlay": 1,
  "recording-ready": 1,
  "mic-level": 1,
  "stream-text-event": 1,
  "stream-phase-event": 1,
  "stream-engine-event": 1,
  "recording-error": 1,
  "settings-changed": 1,
  "theme-changed": 1,
} satisfies Record<string, number>;

/* One fixed frame drives both the route assertions and the evidence captures.
 * Values are already normalized producer buckets, so the last frame is not
 * regenerated by the test. */
const MIC_LEVELS = [
  0.08, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.92, 0.94, 0.96,
  0.98, 1,
];

test("the overlay route turns native events into one live HUD", async ({
  page,
}) => {
  const overlaySettings = {
    ...APP_SETTINGS,
    appearance_material: "solid",
  };
  await installTauriMock(page, {
    responses: {
      get_app_settings: overlaySettings,
      get_settings: overlaySettings,
    },
  });
  await installEventProbe(page);
  await page.goto("/overlay");

  await expect(page.locator("#root")).toBeVisible();
  await expect.poll(() => listenerCounts(page)).toEqual(OVERLAY_LISTENERS);
  await expect(page.getByRole("status")).toHaveCount(0);

  const card = page.getByTestId("hud-card");
  await emitTauriEvent(page, "show-overlay", "recording");
  await expect(card).toHaveText("Starting");
  await expect(card.getByRole("img", { name: "Input level" })).toHaveCount(0);
  await expect(page.locator(".ov-stage")).toHaveAttribute("dir", "ltr");

  /* Frames before recording-ready are stale by definition and must not paint. */
  await emitTauriEvent(page, "mic-level", MIC_LEVELS);
  await expect(card.getByRole("img", { name: "Input level" })).toHaveCount(0);

  await emitTauriEvent(page, "recording-ready", null);
  const meter = card.getByRole("img", { name: "Input level" });
  const bars = meter.locator(":scope > *");
  await expect(meter).toHaveCount(1);
  await expect(bars).toHaveCount(16);
  await expect(bars.first()).toHaveCSS(
    "transform",
    "matrix(1, 0, 0, 0.06, 0, 0)",
  );
  await expect(bars.last()).toHaveCSS(
    "transform",
    "matrix(1, 0, 0, 0.06, 0, 0)",
  );
  await expect(card.getByRole("status")).toHaveCSS("clip-path", "inset(50%)");

  await emitTauriEvent(page, "mic-level", MIC_LEVELS);
  await expect(bars.first()).toHaveCSS(
    "transform",
    "matrix(1, 0, 0, 0.08, 0, 0)",
  );
  await expect(bars.last()).toHaveCSS("transform", "matrix(1, 0, 0, 1, 0, 0)");
  await expect(bars.first()).toHaveCSS("background-color", "rgb(139, 90, 43)");
  const firstBar = bars.first();
  await expect(firstBar).toHaveCSS("transition-duration", "0s");
  await expect(firstBar).toHaveCSS("animation-name", "none");
  await page.emulateMedia({ reducedMotion: "reduce" });
  await expect(firstBar).toHaveCSS("transition-duration", "0s");
  await expect(firstBar).toHaveCSS("animation-name", "none");

  const cancel = page.getByRole("button", { name: "Cancel" });
  await expect(cancel).toHaveCSS("opacity", "0");
  await expect(cancel).toHaveCSS("pointer-events", "none");
  await card.hover();
  await expect
    .poll(() =>
      cancel.evaluate((node) => Number(getComputedStyle(node).opacity)),
    )
    .toBeGreaterThan(0.99);
  await expect(cancel).toHaveCSS("pointer-events", "auto");
  await cancel.click();
  await expect
    .poll(() =>
      page.evaluate(() =>
        Number(localStorage.getItem("tauri-invoke:cancel_operation") ?? "0"),
      ),
    )
    .toBe(1);

  await emitTauriEvent(page, "settings-changed", {
    setting: "appearance_material",
    value: "glass",
  });
  await expect(page.locator("html")).toHaveAttribute("data-material", "glass");

  /* A fresh show starts from the zero frame and cannot inherit the prior run. */
  await emitTauriEvent(page, "show-overlay", "recording");
  await expect(card).toHaveText("Starting");
  await expect(card.getByRole("img", { name: "Input level" })).toHaveCount(0);
  await emitTauriEvent(page, "recording-ready", null);
  await expect(meter).toHaveCount(1);
  await expect(bars).toHaveCount(16);
  await expect(bars.first()).toHaveCSS(
    "transform",
    "matrix(1, 0, 0, 0.06, 0, 0)",
  );
  await expect(bars.last()).toHaveCSS(
    "transform",
    "matrix(1, 0, 0, 0.06, 0, 0)",
  );
  await emitTauriEvent(page, "hide-overlay", null);
  await expect(card).toHaveCount(0);

  /* Errors replace the meter and keep the backend cause in the existing prose. */
  await emitTauriEvent(page, "recording-error", {
    error_type: "no_speech_detected",
  });
  await expect(card.getByRole("alert")).toHaveText("No speech detected");
  await expect(card.getByRole("img", { name: "Input level" })).toHaveCount(0);
  await emitTauriEvent(page, "hide-overlay", null);
  await expect(card.getByRole("alert")).toHaveText("No speech detected");

  /* Streaming keeps its text and working phase, but never shows an input meter
   * after the recorder has handed control to transcription. */
  await emitTauriEvent(page, "show-overlay", "streaming");
  await emitTauriEvent(page, "recording-ready", null);
  await emitTauriEvent(page, "mic-level", MIC_LEVELS);
  await emitTauriEvent(page, "stream-text-event", {
    committed: "Hello",
    tentative: " world",
  });
  await expect(card).toContainText("Hello world");
  await expect(card.getByRole("img", { name: "Input level" })).toHaveCount(1);
  await emitTauriEvent(page, "stream-phase-event", {
    phase: "working",
    kind: "transcribing",
  });
  await expect(card).toContainText("Transcribing");
  await expect(card.getByRole("img", { name: "Input level" })).toHaveCount(0);

  await emitTauriEvent(page, "show-overlay", "idle");
  await expect(page.getByTestId("hud-pill")).toBeVisible();
  await expect(page.getByRole("img", { name: "Input level" })).toHaveCount(0);
});
