//! Generated by `scripts/gen_native_dispatch.py`; do not edit.
//!
//! One arm per command in `collect_commands!`, reading arguments under the
//! names the webview bindings used and running each function where Tauri
//! ran it: sync commands on the main thread, async ones on the runtime.

use serde_json::value::RawValue;
use tauri::{AppHandle, Manager};
use tauri_specta::Event as _;

use super::{encode_plain, off_main_thread, on_main_thread, reply, Args, Fault};

/// Every typed event the core emits, by the name the bindings export.
pub(super) const TYPED_EVENTS: [&str; 33] = [
    crate::upstream_import::UpstreamImportProgressEvent::NAME,
    crate::agent_bridge::AgentBridgeUpdateEvent::NAME,
    crate::agent_panel::AgentPanelStatusChangedEvent::NAME,
    crate::agent_panel::AgentPanelTurnChangedEvent::NAME,
    crate::agent_panel::AgentPanelProposalChangedEvent::NAME,
    crate::modes::ModesChangedEvent::NAME,
    crate::managers::audio::DictationRecordingChangedEvent::NAME,
    crate::managers::history::HistoryUpdatePayload::NAME,
    crate::managers::transcription::StreamTextEvent::NAME,
    crate::managers::transcription::StreamPhaseEvent::NAME,
    crate::managers::transcription::StreamEngineEvent::NAME,
    crate::managers::media_import::AudioImportUpdateEvent::NAME,
    crate::managers::media_import::AudioImportRoutedEvent::NAME,
    crate::recorder::RecorderStateChangedEvent::NAME,
    crate::meeting::types::MeetingSuggestionChangedEvent::NAME,
    crate::meeting::types::MeetingSessionChangedEvent::NAME,
    crate::meeting::types::MeetingSourceHealthChangedEvent::NAME,
    crate::meeting::types::MeetingTranscriptChangedEvent::NAME,
    crate::meeting::types::MeetingNoteChangedEvent::NAME,
    crate::meeting::types::MeetingArtifactChangedEvent::NAME,
    crate::meeting::types::MeetingRemoteJobChangedEvent::NAME,
    crate::meeting::types::MeetingRemovedEvent::NAME,
    crate::cloud_sync::types::CloudSyncChangedEvent::NAME,
    crate::meeting::types::MeetingNavigationRequestedEvent::NAME,
    crate::meeting::detection::DetectionPromptEvent::NAME,
    crate::meeting::detection::DetectionPromptRetractedEvent::NAME,
    crate::meeting::detection::MeetingRitualEvent::NAME,
    crate::meeting::detection::MeetingRitualRetractedEvent::NAME,
    crate::meeting::detection::DetectionStatus::NAME,
    crate::meeting::digest::CaptureRequestedEvent::NAME,
    crate::tray::TraySettingsRequestedEvent::NAME,
    crate::tray::TrayCopyFailedEvent::NAME,
    crate::query::QueryLinkRequestedEvent::NAME,
];

pub(super) async fn call(
    app: &AppHandle,
    method: &str,
    params: Option<&RawValue>,
) -> Result<String, Fault> {
    match method {
        "get_upstream_import_status" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::upstream_import::get_upstream_import_status(handle.clone()))).await?
        }
        "import_legacy_app" => {
            let mut args = Args::parse(params)?;
            let selection = args.take("selection")?;
            reply(crate::upstream_import::import_legacy_app(app.clone(), app.state(), app.state(), selection).await)
        }
        "revert_upstream_import_settings" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::upstream_import::revert_upstream_import_settings(handle.clone()))).await?
        }
        "get_identity_adoption_status" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::identity_adoption::get_identity_adoption_status(handle.clone()))).await?
        }
        "revert_identity_adoption" => {
            reply(crate::identity_adoption::revert_identity_adoption(app.clone(), app.state()).await)
        }
        "get_agent_bridge_status" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::agent_bridge::get_agent_bridge_status(handle.state()))).await?
        }
        "get_agent_bridge_sessions" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::agent_bridge::get_agent_bridge_sessions(handle.state()))).await?
        }
        "get_agent_bridge_requests" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::agent_bridge::get_agent_bridge_requests(handle.state()))).await?
        }
        "get_agent_bridge_pending_messages" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::agent_bridge::get_agent_bridge_pending_messages(handle.state()))).await?
        }
        "set_agent_bridge_master" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_bridge::set_agent_bridge_master(handle.clone(), handle.state(), enabled))).await?
        }
        "set_agent_bridge_agent_enabled" => {
            let mut args = Args::parse(params)?;
            let agent = args.take("agent")?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_bridge::set_agent_bridge_agent_enabled(handle.clone(), handle.state(), agent, enabled))).await?
        }
        "authorize_agent_bridge_project" => {
            let mut args = Args::parse(params)?;
            let selected_path = args.take("selectedPath")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_bridge::authorize_agent_bridge_project(handle.clone(), handle.state(), selected_path))).await?
        }
        "remove_agent_bridge_project" => {
            let mut args = Args::parse(params)?;
            let canonical_project_hash = args.take("canonicalProjectHash")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_bridge::remove_agent_bridge_project(handle.clone(), handle.state(), canonical_project_hash))).await?
        }
        "create_agent_bridge_reply_preview" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            let text = args.take("text")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_bridge::create_agent_bridge_reply_preview(handle.state(), session_id, text))).await?
        }
        "confirm_agent_bridge_reply" => {
            let mut args = Args::parse(params)?;
            let pending_id = args.take("pendingId")?;
            let session_id = args.take("sessionId")?;
            let text = args.take("text")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_bridge::confirm_agent_bridge_reply(handle.state(), pending_id, session_id, text))).await?
        }
        "cancel_agent_bridge_message" => {
            let mut args = Args::parse(params)?;
            let pending_id = args.take("pendingId")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_bridge::cancel_agent_bridge_message(handle.state(), pending_id))).await?
        }
        "dismiss_agent_bridge_request" => {
            let mut args = Args::parse(params)?;
            let request_id = args.take("requestId")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_bridge::dismiss_agent_bridge_request(handle.state(), request_id))).await?
        }
        "create_agent_bridge_permission_rule" => {
            let mut args = Args::parse(params)?;
            let request_id = args.take("requestId")?;
            let decision = args.take("decision")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_bridge::create_agent_bridge_permission_rule(handle.clone(), handle.state(), request_id, decision))).await?
        }
        "delete_agent_bridge_permission_rule" => {
            let mut args = Args::parse(params)?;
            let rule_id = args.take("ruleId")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_bridge::delete_agent_bridge_permission_rule(handle.clone(), handle.state(), rule_id))).await?
        }
        "respond_agent_bridge_permission" => {
            let mut args = Args::parse(params)?;
            let request_id = args.take("requestId")?;
            let rule_id = args.take("ruleId")?;
            let decision = args.take("decision")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_bridge::respond_agent_bridge_permission(handle.clone(), handle.state(), request_id, rule_id, decision))).await?
        }
        "get_agent_bridge_hook_snippet" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_bridge::get_agent_bridge_hook_snippet(handle.clone()))).await?
        }
        "agent_panel_status" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_panel::agent_panel_status(handle.state()))).await?
        }
        "agent_panel_send_turn" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::agent_panel::agent_panel_send_turn(app.state(), request).await)
        }
        "agent_panel_cancel_turn" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::agent_panel::agent_panel_cancel_turn(app.state(), request).await)
        }
        "agent_panel_apply_change" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_panel::agent_panel_apply_change(handle.state(), request))).await?
        }
        "agent_panel_undo_change" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_panel::agent_panel_undo_change(handle.state(), request))).await?
        }
        "agent_panel_apply_action" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::agent_panel::agent_panel_apply_action(app.state(), app.state(), request).await)
        }
        "agent_panel_dismiss_action" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::agent_panel::agent_panel_dismiss_action(app.state(), app.state(), request).await)
        }
        "agent_chat_history_list" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_panel::agent_chat_history_list(handle.state()))).await?
        }
        "agent_chat_open" => {
            let mut args = Args::parse(params)?;
            let conversation_id = args.take("conversationId")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_panel::agent_chat_open(handle.state(), conversation_id))).await?
        }
        "agent_chat_new" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_panel::agent_chat_new(handle.state()))).await?
        }
        "agent_panel_public_identity" => {
            reply(crate::agent_panel::agent_panel_public_identity(app.state()).await)
        }
        "change_agent_panel_enabled_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_panel::change_agent_panel_enabled_setting(handle.clone(), enabled))).await?
        }
        "set_agent_panel_pairing" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_panel::set_agent_panel_pairing(handle.clone(), request))).await?
        }
        "clear_agent_panel_pairing" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::agent_panel::clear_agent_panel_pairing(handle.clone()))).await?
        }
        "agent_panel_test_connection" => {
            reply(crate::agent_panel::agent_panel_test_connection(app.clone(), app.state()).await)
        }
        "get_modes" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::modes::get_modes(handle.clone()))).await?
        }
        "set_active_mode" => {
            let mut args = Args::parse(params)?;
            let mode_id = args.take("modeId")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::modes::set_active_mode(handle.clone(), mode_id))).await?
        }
        "upsert_mode" => {
            let mut args = Args::parse(params)?;
            let mode = args.take("mode")?;
            let expected_revision = args.take("expectedRevision")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::modes::upsert_mode(handle.clone(), mode, expected_revision))).await?
        }
        "delete_mode" => {
            let mut args = Args::parse(params)?;
            let mode_id = args.take("modeId")?;
            let expected_revision = args.take("expectedRevision")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::modes::delete_mode(handle.clone(), mode_id, expected_revision))).await?
        }
        "reorder_modes" => {
            let mut args = Args::parse(params)?;
            let ordered_ids = args.take("orderedIds")?;
            let expected_revision = args.take("expectedRevision")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::modes::reorder_modes(handle.clone(), ordered_ids, expected_revision))).await?
        }
        "list_vocabulary_entries" => {
            let mut args = Args::parse(params)?;
            let scope = args.take("scope")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::vocabulary::list_vocabulary_entries(handle.clone(), scope))).await?
        }
        "capture_mode_activation_rule" => {
            let mut args = Args::parse(params)?;
            let mode_id = args.take("modeId")?;
            let expected_revision = args.take("expectedRevision")?;
            reply(crate::modes::capture_mode_activation_rule(app.clone(), mode_id, expected_revision).await)
        }
        "remove_mode_activation_rule" => {
            let mut args = Args::parse(params)?;
            let app_id = args.take("appId")?;
            let expected_revision = args.take("expectedRevision")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::modes::remove_mode_activation_rule(handle.clone(), app_id, expected_revision))).await?
        }
        "capture_mode_website_activation_rule" => {
            let mut args = Args::parse(params)?;
            let mode_id = args.take("modeId")?;
            let match_kind = args.take("matchKind")?;
            let expected_revision = args.take("expectedRevision")?;
            reply(crate::modes::capture_mode_website_activation_rule(app.clone(), mode_id, match_kind, expected_revision).await)
        }
        "remove_mode_website_activation_rule" => {
            let mut args = Args::parse(params)?;
            let host = args.take("host")?;
            let match_kind = args.take("matchKind")?;
            let expected_revision = args.take("expectedRevision")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::modes::remove_mode_website_activation_rule(handle.clone(), host, match_kind, expected_revision))).await?
        }
        "update_vocabulary_entries" => {
            let mut args = Args::parse(params)?;
            let scope = args.take("scope")?;
            let entries = args.take("entries")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::vocabulary::update_vocabulary_entries(handle.clone(), scope, entries))).await?
        }
        "preview_vocabulary_csv" => {
            let mut args = Args::parse(params)?;
            let scope = args.take("scope")?;
            let csv_text = args.take("csvText")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::vocabulary::preview_vocabulary_csv(handle.clone(), scope, csv_text))).await?
        }
        "apply_vocabulary_csv" => {
            let mut args = Args::parse(params)?;
            let scope = args.take("scope")?;
            let csv_text = args.take("csvText")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::vocabulary::apply_vocabulary_csv(handle.clone(), scope, csv_text))).await?
        }
        "export_vocabulary_csv" => {
            let mut args = Args::parse(params)?;
            let scope = args.take("scope")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::vocabulary::export_vocabulary_csv(handle.clone(), scope))).await?
        }
        "update_emoji_replacements" => {
            let mut args = Args::parse(params)?;
            let replacements = args.take("replacements")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::vocabulary::update_emoji_replacements(handle.clone(), replacements))).await?
        }
        "update_emoji_replacements_enabled" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::vocabulary::update_emoji_replacements_enabled(handle.clone(), enabled))).await?
        }
        "add_vocabulary_correction" => {
            let mut args = Args::parse(params)?;
            let spoken = args.take("spoken")?;
            let written = args.take("written")?;
            let scope = args.take("scope")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::vocabulary::add_vocabulary_correction(handle.clone(), spoken, written, scope))).await?
        }
        "get_text_replacements" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::vocabulary::get_text_replacements(handle.clone()))).await?
        }
        "save_text_replacements" => {
            let mut args = Args::parse(params)?;
            let rules = args.take("rules")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::vocabulary::save_text_replacements(handle.clone(), rules))).await?
        }
        "reset_text_replacements" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::vocabulary::reset_text_replacements(handle.clone()))).await?
        }
        "update_text_replacements_enabled" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::vocabulary::update_text_replacements_enabled(handle.clone(), enabled))).await?
        }
        "update_spoken_edits_enabled" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::vocabulary::update_spoken_edits_enabled(handle.clone(), enabled))).await?
        }
        "hud_pill_state" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::hud::hud_pill_state(handle.clone()))).await?
        }
        "set_hud_pill_enabled" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::hud::set_hud_pill_enabled(handle.clone(), enabled))).await?
        }
        "set_hud_pill_position" => {
            let mut args = Args::parse(params)?;
            let position = args.take("position")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::hud::set_hud_pill_position(handle.clone(), position))).await?
        }
        "hud_toggle_recording" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::hud::hud_toggle_recording(handle.clone()))).await?
        }
        "hud_open_mode_menu" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::hud::hud_open_mode_menu(handle.clone()))).await?
        }
        "get_persona_samples" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::persona::get_persona_samples(handle.clone()))).await?
        }
        "save_persona_samples" => {
            let mut args = Args::parse(params)?;
            let samples = args.take("samples")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::persona::save_persona_samples(handle.clone(), samples))).await?
        }
        "list_snippets" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::snippets::list_snippets(handle.clone()))).await?
        }
        "upsert_snippet" => {
            let mut args = Args::parse(params)?;
            let snippet = args.take("snippet")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::snippets::upsert_snippet(handle.clone(), snippet))).await?
        }
        "delete_snippet" => {
            let mut args = Args::parse(params)?;
            let snippet_id = args.take("snippetId")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::snippets::delete_snippet(handle.clone(), snippet_id))).await?
        }
        "set_snippet_enabled" => {
            let mut args = Args::parse(params)?;
            let snippet_id = args.take("snippetId")?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::snippets::set_snippet_enabled(handle.clone(), snippet_id, enabled))).await?
        }
        "set_snippets_enabled" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::snippets::set_snippets_enabled(handle.clone(), enabled))).await?
        }
        "change_context_policy_ceiling_setting" => {
            let mut args = Args::parse(params)?;
            let ceiling = args.take("ceiling")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::settings::change_context_policy_ceiling_setting(handle.clone(), ceiling))).await?
        }
        "change_context_url_capture_enabled_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::settings::change_context_url_capture_enabled_setting(handle.clone(), enabled))).await?
        }
        "change_external_query_enabled_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::settings::change_external_query_enabled_setting(handle.clone(), enabled))).await?
        }
        "change_external_mutations_enabled_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::settings::change_external_mutations_enabled_setting(handle.clone(), enabled))).await?
        }
        "change_meeting_local_engine_setting" => {
            let mut args = Args::parse(params)?;
            let engine = args.take("engine")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::settings::change_meeting_local_engine_setting(handle.clone(), engine))).await?
        }
        "change_meeting_remote_intelligence_enabled_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::settings::change_meeting_remote_intelligence_enabled_setting(handle.clone(), enabled))).await?
        }
        "change_meeting_digest_enabled_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::settings::change_meeting_digest_enabled_setting(handle.clone(), enabled))).await?
        }
        "change_meeting_digest_minute_of_day_setting" => {
            let mut args = Args::parse(params)?;
            let minute_of_day = args.take("minuteOfDay")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::settings::change_meeting_digest_minute_of_day_setting(handle.clone(), minute_of_day))).await?
        }
        "accept_cloud_stt_provider_consent" => {
            let mut args = Args::parse(params)?;
            let provider = args.take("provider")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::settings::accept_cloud_stt_provider_consent(handle.clone(), provider))).await?
        }
        "accept_post_process_provider_consent" => {
            let mut args = Args::parse(params)?;
            let provider_id = args.take("providerId")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::settings::accept_post_process_provider_consent(handle.clone(), provider_id))).await?
        }
        "change_command_mode_enabled_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::command_mode::change_command_mode_enabled_setting(handle.clone(), enabled))).await?
        }
        "change_binding" => {
            let mut args = Args::parse(params)?;
            let id = args.take("id")?;
            let binding = args.take("binding")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_binding(handle.clone(), id, binding))).await?
        }
        "reset_binding" => {
            let mut args = Args::parse(params)?;
            let id = args.take("id")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::reset_binding(handle.clone(), id))).await?
        }
        "change_ptt_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_ptt_setting(handle.clone(), enabled))).await?
        }
        "change_audio_feedback_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_audio_feedback_setting(handle.clone(), enabled))).await?
        }
        "change_audio_feedback_volume_setting" => {
            let mut args = Args::parse(params)?;
            let volume = args.take("volume")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_audio_feedback_volume_setting(handle.clone(), volume))).await?
        }
        "change_sound_theme_setting" => {
            let mut args = Args::parse(params)?;
            let theme = args.take("theme")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_sound_theme_setting(handle.clone(), theme))).await?
        }
        "change_theme_setting" => {
            let mut args = Args::parse(params)?;
            let theme = args.take("theme")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_theme_setting(handle.clone(), theme))).await?
        }
        "change_appearance_material_setting" => {
            let mut args = Args::parse(params)?;
            let material = args.take("material")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_appearance_material_setting(handle.clone(), material))).await?
        }
        "change_start_hidden_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_start_hidden_setting(handle.clone(), enabled))).await?
        }
        "change_autostart_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_autostart_setting(handle.clone(), enabled))).await?
        }
        "change_translate_to_english_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_translate_to_english_setting(handle.clone(), enabled))).await?
        }
        "change_selected_language_setting" => {
            let mut args = Args::parse(params)?;
            let language = args.take("language")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_selected_language_setting(handle.clone(), language))).await?
        }
        "change_overlay_position_setting" => {
            let mut args = Args::parse(params)?;
            let position = args.take("position")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_overlay_position_setting(handle.clone(), position))).await?
        }
        "change_english_spelling_setting" => {
            let mut args = Args::parse(params)?;
            let spelling = args.take("spelling")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_english_spelling_setting(handle.clone(), spelling))).await?
        }
        "change_overlay_style_setting" => {
            let mut args = Args::parse(params)?;
            let style = args.take("style")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_overlay_style_setting(handle.clone(), style))).await?
        }
        "change_debug_mode_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_debug_mode_setting(handle.clone(), enabled))).await?
        }
        "change_word_correction_threshold_setting" => {
            let mut args = Args::parse(params)?;
            let threshold = args.take("threshold")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_word_correction_threshold_setting(handle.clone(), threshold))).await?
        }
        "change_extra_recording_buffer_setting" => {
            let mut args = Args::parse(params)?;
            let ms = args.take("ms")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_extra_recording_buffer_setting(handle.clone(), ms))).await?
        }
        "get_available_typing_tools" => {
            on_main_thread(app, move || encode_plain(crate::shortcut::get_available_typing_tools())).await?
        }
        "change_external_script_path_setting" => {
            let mut args = Args::parse(params)?;
            let path = args.take("path")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_external_script_path_setting(handle.clone(), path))).await?
        }
        "change_post_process_enabled_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_post_process_enabled_setting(handle.clone(), enabled))).await?
        }
        "change_experimental_enabled_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_experimental_enabled_setting(handle.clone(), enabled))).await?
        }
        "change_post_process_base_url_setting" => {
            let mut args = Args::parse(params)?;
            let provider_id = args.take("providerId")?;
            let base_url = args.take("baseUrl")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_post_process_base_url_setting(handle.clone(), provider_id, base_url))).await?
        }
        "get_provider_secret_state" => {
            let mut args = Args::parse(params)?;
            let kind = args.take("kind")?;
            let provider_id = args.take("providerId")?;
            reply(crate::secrets::get_provider_secret_state(app.clone(), app.state(), kind, provider_id).await)
        }
        "set_provider_secret" => {
            let mut args = Args::parse(params)?;
            let kind = args.take("kind")?;
            let provider_id = args.take("providerId")?;
            let secret = args.take("secret")?;
            reply(crate::secrets::set_provider_secret(app.clone(), app.state(), kind, provider_id, secret).await)
        }
        "delete_provider_secret" => {
            let mut args = Args::parse(params)?;
            let kind = args.take("kind")?;
            let provider_id = args.take("providerId")?;
            reply(crate::secrets::delete_provider_secret(app.clone(), app.state(), kind, provider_id).await)
        }
        "verify_stt_provider_secret" => {
            let mut args = Args::parse(params)?;
            let provider = args.take("provider")?;
            reply(crate::secrets::verify_stt_provider_secret(app.clone(), app.state(), provider).await)
        }
        "change_post_process_model_setting" => {
            let mut args = Args::parse(params)?;
            let provider_id = args.take("providerId")?;
            let model = args.take("model")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_post_process_model_setting(handle.clone(), provider_id, model))).await?
        }
        "set_post_process_provider" => {
            let mut args = Args::parse(params)?;
            let provider_id = args.take("providerId")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::set_post_process_provider(handle.clone(), provider_id))).await?
        }
        "discover_post_process_model_catalog" => {
            let mut args = Args::parse(params)?;
            let provider_id = args.take("providerId")?;
            encode_plain(crate::shortcut::discover_post_process_model_catalog(app.clone(), provider_id).await)
        }
        "add_post_process_prompt" => {
            let mut args = Args::parse(params)?;
            let name = args.take("name")?;
            let prompt = args.take("prompt")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::add_post_process_prompt(handle.clone(), name, prompt))).await?
        }
        "update_post_process_prompt" => {
            let mut args = Args::parse(params)?;
            let id = args.take("id")?;
            let name = args.take("name")?;
            let prompt = args.take("prompt")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::update_post_process_prompt(handle.clone(), id, name, prompt))).await?
        }
        "delete_post_process_prompt" => {
            let mut args = Args::parse(params)?;
            let id = args.take("id")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::delete_post_process_prompt(handle.clone(), id))).await?
        }
        "set_post_process_selected_prompt" => {
            let mut args = Args::parse(params)?;
            let id = args.take("id")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::set_post_process_selected_prompt(handle.clone(), id))).await?
        }
        "suspend_all_bindings" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::suspend_all_bindings(handle.clone()))).await?
        }
        "resume_all_bindings" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::resume_all_bindings(handle.clone()))).await?
        }
        "change_mute_while_recording_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_mute_while_recording_setting(handle.clone(), enabled))).await?
        }
        "change_append_trailing_space_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_append_trailing_space_setting(handle.clone(), enabled))).await?
        }
        "change_lazy_stream_close_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_lazy_stream_close_setting(handle.clone(), enabled))).await?
        }
        "change_vad_enabled_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_vad_enabled_setting(handle.clone(), enabled))).await?
        }
        "change_filler_word_removal_enabled_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_filler_word_removal_enabled_setting(handle.clone(), enabled))).await?
        }
        "change_app_language_setting" => {
            let mut args = Args::parse(params)?;
            let language = args.take("language")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_app_language_setting(handle.clone(), language))).await?
        }
        "change_show_whats_new_on_update_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_show_whats_new_on_update_setting(handle.clone(), enabled))).await?
        }
        "change_whats_new_last_seen_version_setting" => {
            let mut args = Args::parse(params)?;
            let version = args.take("version")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_whats_new_last_seen_version_setting(handle.clone(), version))).await?
        }
        "change_keyboard_implementation_setting" => {
            let mut args = Args::parse(params)?;
            let implementation = args.take("implementation")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_keyboard_implementation_setting(handle.clone(), implementation))).await?
        }
        "get_keyboard_implementation" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::shortcut::get_keyboard_implementation(handle.clone()))).await?
        }
        "change_show_tray_icon_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_show_tray_icon_setting(handle.clone(), enabled))).await?
        }
        "change_transcribe_accelerator_setting" => {
            let mut args = Args::parse(params)?;
            let accelerator = args.take("accelerator")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_transcribe_accelerator_setting(handle.clone(), accelerator))).await?
        }
        "change_ort_accelerator_setting" => {
            let mut args = Args::parse(params)?;
            let accelerator = args.take("accelerator")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_ort_accelerator_setting(handle.clone(), accelerator))).await?
        }
        "change_transcribe_gpu_device" => {
            let mut args = Args::parse(params)?;
            let device = args.take("device")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::change_transcribe_gpu_device(handle.clone(), device))).await?
        }
        "get_available_accelerators" => {
            encode_plain(crate::shortcut::get_available_accelerators().await)
        }
        "start_handy_keys_recording" => {
            let mut args = Args::parse(params)?;
            let binding_id = args.take("bindingId")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::handy_keys::start_handy_keys_recording(handle.clone(), binding_id))).await?
        }
        "stop_handy_keys_recording" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::shortcut::handy_keys::stop_handy_keys_recording(handle.clone()))).await?
        }
        "get_secure_input_status" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::secure_input::get_secure_input_status(handle.clone()))).await?
        }
        "run_keyboard_diagnostic" => {
            let mut args = Args::parse(params)?;
            let duration_secs = args.take("durationSecs")?;
            reply(crate::secure_input::run_keyboard_diagnostic(duration_secs).await)
        }
        "show_main_window_command" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::show_main_window_command(handle.clone()))).await?
        }
        "cancel_operation" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::cancel_operation(handle.clone()))).await?
        }
        "is_portable" => {
            on_main_thread(app, move || encode_plain(crate::commands::is_portable())).await?
        }
        "get_app_dir_path" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::get_app_dir_path(handle.clone()))).await?
        }
        "get_app_settings" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::get_app_settings(handle.clone()))).await?
        }
        "get_default_settings" => {
            on_main_thread(app, move || reply(crate::commands::get_default_settings())).await?
        }
        "get_context_diagnostics" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::context::get_context_diagnostics(handle.clone()))).await?
        }
        "get_log_dir_path" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::get_log_dir_path(handle.clone()))).await?
        }
        "set_log_level" => {
            let mut args = Args::parse(params)?;
            let level = args.take("level")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::set_log_level(handle.clone(), level))).await?
        }
        "open_recordings_folder" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::open_recordings_folder(handle.clone()))).await?
        }
        "open_log_dir" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::open_log_dir(handle.clone()))).await?
        }
        "open_app_data_dir" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::open_app_data_dir(handle.clone()))).await?
        }
        "open_license_notices" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::open_license_notices(handle.clone()))).await?
        }
        "check_apple_intelligence_available" => {
            on_main_thread(app, move || encode_plain(crate::commands::check_apple_intelligence_available())).await?
        }
        "initialize_enigo" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::initialize_enigo(handle.clone()))).await?
        }
        "initialize_shortcuts" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::initialize_shortcuts(handle.clone()))).await?
        }
        "get_available_models" => {
            reply(crate::commands::models::get_available_models(app.state()).await)
        }
        "get_model_info" => {
            let mut args = Args::parse(params)?;
            let model_id = args.take("modelId")?;
            reply(crate::commands::models::get_model_info(app.state(), model_id).await)
        }
        "download_model" => {
            let mut args = Args::parse(params)?;
            let model_id = args.take("modelId")?;
            reply(crate::commands::models::download_model(app.clone(), app.state(), model_id).await)
        }
        "delete_model" => {
            let mut args = Args::parse(params)?;
            let model_id = args.take("modelId")?;
            reply(crate::commands::models::delete_model(app.clone(), app.state(), app.state(), model_id).await)
        }
        "cancel_download" => {
            let mut args = Args::parse(params)?;
            let model_id = args.take("modelId")?;
            reply(crate::commands::models::cancel_download(app.state(), model_id).await)
        }
        "set_active_model" => {
            let mut args = Args::parse(params)?;
            let model_id = args.take("modelId")?;
            reply(crate::commands::models::set_active_model(app.clone(), app.state(), app.state(), model_id).await)
        }
        "get_current_model" => {
            reply(crate::commands::models::get_current_model(app.clone()).await)
        }
        "get_transcription_model_status" => {
            reply(crate::commands::models::get_transcription_model_status(app.state()).await)
        }
        "is_model_loading" => {
            reply(crate::commands::models::is_model_loading(app.state()).await)
        }
        "rescan_local_models" => {
            reply(crate::commands::models::rescan_local_models(app.state()).await)
        }
        "update_microphone_mode" => {
            let mut args = Args::parse(params)?;
            let always_on = args.take("alwaysOn")?;
            reply(crate::commands::audio::update_microphone_mode(app.clone(), always_on).await)
        }
        "get_microphone_mode" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::audio::get_microphone_mode(handle.clone()))).await?
        }
        "get_windows_microphone_permission_status" => {
            on_main_thread(app, move || encode_plain(crate::commands::audio::get_windows_microphone_permission_status())).await?
        }
        "open_microphone_privacy_settings" => {
            on_main_thread(app, move || reply(crate::commands::audio::open_microphone_privacy_settings())).await?
        }
        "get_available_microphones" => {
            reply(crate::commands::audio::get_available_microphones().await)
        }
        "set_selected_microphone" => {
            let mut args = Args::parse(params)?;
            let device_name = args.take("deviceName")?;
            reply(crate::commands::audio::set_selected_microphone(app.clone(), device_name).await)
        }
        "get_selected_microphone" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::audio::get_selected_microphone(handle.clone()))).await?
        }
        "get_available_output_devices" => {
            reply(crate::commands::audio::get_available_output_devices().await)
        }
        "set_selected_output_device" => {
            let mut args = Args::parse(params)?;
            let device_name = args.take("deviceName")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::audio::set_selected_output_device(handle.clone(), device_name))).await?
        }
        "get_selected_output_device" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::audio::get_selected_output_device(handle.clone()))).await?
        }
        "play_test_sound" => {
            let mut args = Args::parse(params)?;
            let sound_type = args.take("soundType")?;
            encode_plain(crate::commands::audio::play_test_sound(app.clone(), sound_type).await)
        }
        "check_custom_sounds" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::audio::check_custom_sounds(handle.clone()))).await?
        }
        "set_clamshell_microphone" => {
            let mut args = Args::parse(params)?;
            let device_name = args.take("deviceName")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::audio::set_clamshell_microphone(handle.clone(), device_name))).await?
        }
        "get_clamshell_microphone" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::audio::get_clamshell_microphone(handle.clone()))).await?
        }
        "is_recording" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::audio::is_recording(handle.clone()))).await?
        }
        "get_microphone_channels" => {
            let mut args = Args::parse(params)?;
            let device_name = args.take("deviceName")?;
            reply(crate::commands::audio::get_microphone_channels(device_name).await)
        }
        "set_selected_channel" => {
            let mut args = Args::parse(params)?;
            let channel = args.take("channel")?;
            reply(crate::commands::audio::set_selected_channel(app.clone(), channel).await)
        }
        "set_model_unload_timeout" => {
            let mut args = Args::parse(params)?;
            let timeout = args.take("timeout")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::transcription::set_model_unload_timeout(handle.clone(), timeout))).await?
        }
        "get_model_load_status" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::transcription::get_model_load_status(handle.state()))).await?
        }
        "unload_model_manually" => {
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::transcription::unload_model_manually(handle.state()))).await?
        }
        "import_audio_file" => {
            let mut args = Args::parse(params)?;
            let path = args.take("path")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::media_import::import_audio_file(handle.clone(), handle.state(), path))).await?
        }
        "cancel_audio_import" => {
            let mut args = Args::parse(params)?;
            let job_id = args.take("jobId")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::media_import::cancel_audio_import(handle.state(), job_id))).await?
        }
        "list_audio_import_jobs" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::media_import::list_audio_import_jobs(handle.state()))).await?
        }
        "recorder_preflight" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::recorder::recorder_preflight(handle.state()))).await?
        }
        "recorder_preview_start" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::recorder::recorder_preview_start(app.state(), request).await)
        }
        "recorder_preview_stop" => {
            reply(crate::commands::recorder::recorder_preview_stop(app.state()).await)
        }
        "recorder_start" => {
            reply(crate::commands::recorder::recorder_start(app.state()).await)
        }
        "recorder_pause" => {
            reply(crate::commands::recorder::recorder_pause(app.state()).await)
        }
        "recorder_resume" => {
            reply(crate::commands::recorder::recorder_resume(app.state()).await)
        }
        "recorder_stop" => {
            reply(crate::commands::recorder::recorder_stop(app.state()).await)
        }
        "recorder_cancel" => {
            reply(crate::commands::recorder::recorder_cancel(app.state()).await)
        }
        "voice_identity_status" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::voice_identity::voice_identity_status(app.state(), session_id).await)
        }
        "voice_identify_speaker" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::voice_identity::voice_identify_speaker(app.state(), request).await)
        }
        "voice_enroll_profile" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::voice_identity::voice_enroll_profile(app.state(), request).await)
        }
        "voice_remove_profile" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::voice_identity::voice_remove_profile(app.state(), request).await)
        }
        "get_history_stats" => {
            reply(crate::commands::history::get_history_stats(app.clone(), app.state()).await)
        }
        "get_history_trend" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::history::get_history_trend(app.clone(), app.state(), request).await)
        }
        "get_history_entries" => {
            let mut args = Args::parse(params)?;
            let cursor = args.take("cursor")?;
            let limit = args.take("limit")?;
            reply(crate::commands::history::get_history_entries(app.clone(), app.state(), cursor, limit).await)
        }
        "search_history_entries" => {
            let mut args = Args::parse(params)?;
            let query = args.take("query")?;
            let cursor = args.take("cursor")?;
            let limit = args.take("limit")?;
            reply(crate::commands::history::search_history_entries(app.clone(), app.state(), query, cursor, limit).await)
        }
        "get_history_run_receipts" => {
            let mut args = Args::parse(params)?;
            let history_id = args.take("historyId")?;
            reply(crate::commands::history::get_history_run_receipts(app.clone(), app.state(), history_id).await)
        }
        "toggle_history_entry_saved" => {
            let mut args = Args::parse(params)?;
            let id = args.take("id")?;
            reply(crate::commands::history::toggle_history_entry_saved(app.clone(), app.state(), id).await)
        }
        "read_history_audio_chunk" => {
            let mut args = Args::parse(params)?;
            let history_id = args.take("historyId")?;
            let offset = args.take("offset")?;
            reply(crate::commands::history::read_history_audio_chunk(app.state(), history_id, offset).await)
        }
        "delete_history_entry" => {
            let mut args = Args::parse(params)?;
            let id = args.take("id")?;
            reply(crate::commands::history::delete_history_entry(app.clone(), app.state(), id).await)
        }
        "retry_history_entry_transcription" => {
            let mut args = Args::parse(params)?;
            let id = args.take("id")?;
            reply(crate::commands::history::retry_history_entry_transcription(app.clone(), app.state(), app.state(), id).await)
        }
        "reprocess_history_entry" => {
            let mut args = Args::parse(params)?;
            let id = args.take("id")?;
            let mode_id = args.take("modeId")?;
            reply(crate::commands::history::reprocess_history_entry(app.clone(), app.state(), app.state(), id, mode_id).await)
        }
        "update_history_limit" => {
            let mut args = Args::parse(params)?;
            let limit = args.take("limit")?;
            reply(crate::commands::history::update_history_limit(app.clone(), app.state(), limit).await)
        }
        "update_recording_retention_period" => {
            let mut args = Args::parse(params)?;
            let period = args.take("period")?;
            reply(crate::commands::history::update_recording_retention_period(app.clone(), app.state(), period).await)
        }
        "history_storage_status" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::history::history_storage_status(handle.clone()))).await?
        }
        "meeting_suggestions_list" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::meeting::meeting_suggestions_list(handle.state()))).await?
        }
        "meeting_preflight_create" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_preflight_create(app.state(), app.state(), request).await)
        }
        "meeting_preflight_refresh" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_preflight_refresh(app.state(), request).await)
        }
        "meeting_preflight_cancel" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_preflight_cancel(app.state(), request).await)
        }
        "meeting_start" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_start(app.state(), app.state(), request).await)
        }
        "meeting_consent_panel_start" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_consent_panel_start(app.state(), app.state(), request).await)
        }
        "meeting_consent_panel_active_state" => {
            reply(crate::commands::meeting::meeting_consent_panel_active_state(app.state()).await)
        }
        "meeting_consent_panel_forget_series" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::meeting::meeting_consent_panel_forget_series(app.state(), session_id).await)
        }
        "meeting_consent_panel_fit_disclosure" => {
            let mut args = Args::parse(params)?;
            let note = args.take("note")?;
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::meeting::meeting_consent_panel_fit_disclosure(handle.clone(), note))).await?
        }
        "meeting_announce_disclosure" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            let line = args.take("line")?;
            reply(crate::commands::meeting::meeting_announce_disclosure(app.state(), session_id, line).await)
        }
        "meeting_trash_list" => {
            reply(crate::commands::meeting::meeting_trash_list(app.state()).await)
        }
        "meeting_trash_restore" => {
            let mut args = Args::parse(params)?;
            let job_id = args.take("jobId")?;
            reply(crate::commands::meeting::meeting_trash_restore(app.state(), job_id).await)
        }
        "meeting_pause" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_pause(app.state(), request).await)
        }
        "meeting_resume" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_resume(app.state(), request).await)
        }
        "meeting_stop" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            let surface = args.take("surface")?;
            reply(crate::commands::meeting::meeting_stop(app.state(), app.state(), request, surface).await)
        }
        "meeting_discard" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_discard(app.state(), app.state(), request).await)
        }
        "meeting_import_recording" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_import_recording(app.state(), request).await)
        }
        "meeting_import_transcript" => {
            let mut args = Args::parse(params)?;
            let path = args.take("path")?;
            reply(crate::commands::meeting::meeting_import_transcript(app.state(), path).await)
        }
        "meeting_recovery_list" => {
            reply(crate::commands::meeting::meeting_recovery_list(app.state()).await)
        }
        "meeting_recovery_finalize" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_recovery_finalize(app.state(), request).await)
        }
        "meeting_list" => {
            let mut args = Args::parse(params)?;
            let cursor_utc_ms = args.take("cursorUtcMs")?;
            let limit = args.take("limit")?;
            let filter = args.take("filter")?;
            reply(crate::commands::meeting::meeting_list(app.state(), cursor_utc_ms, limit, filter).await)
        }
        "meeting_trend" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_trend(app.state(), request).await)
        }
        "meeting_get" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::meeting::meeting_get(app.state(), session_id).await)
        }
        "meeting_search" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_search(app.state(), request).await)
        }
        "meeting_title_set" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_title_set(app.state(), request).await)
        }
        "meeting_speaker_rename" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_speaker_rename(app.state(), request).await)
        }
        "meeting_speaker_merge" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_speaker_merge(app.state(), request).await)
        }
        "meeting_segment_edit" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_segment_edit(app.state(), request).await)
        }
        "meeting_note_create" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_note_create(app.state(), request).await)
        }
        "meeting_note_update" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_note_update(app.state(), request).await)
        }
        "meeting_note_delete" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_note_delete(app.state(), request).await)
        }
        "meeting_artifacts_regenerate" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_artifacts_regenerate(app.state(), request).await)
        }
        "meeting_question_forget" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            let question_id = args.take("questionId")?;
            reply(crate::commands::meeting::meeting_question_forget(app.state(), request, question_id).await)
        }
        "meeting_export" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_export(app.state(), request).await)
        }
        "produce_ledger_html" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::meeting::produce_ledger_html(app.state(), session_id).await)
        }
        "meeting_delete" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_delete(app.state(), request).await)
        }
        "meeting_retention_get" => {
            reply(crate::commands::meeting::meeting_retention_get(app.state()).await)
        }
        "meeting_local_engine_status" => {
            let handle = app.clone();
            off_main_thread(move || encode_plain(crate::commands::meeting::meeting_local_engine_status(handle.state()))).await?
        }
        "meeting_retention_set" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_retention_set(app.state(), request).await)
        }
        "meeting_remote_cancel" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_remote_cancel(app.state(), request).await)
        }
        "get_meeting_analytics" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::meeting::get_meeting_analytics(app.state(), session_id).await)
        }
        "list_keyword_trackers" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::meeting::list_keyword_trackers(handle.clone()))).await?
        }
        "save_keyword_trackers" => {
            let mut args = Args::parse(params)?;
            let trackers = args.take("trackers")?;
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::meeting::save_keyword_trackers(handle.clone(), trackers))).await?
        }
        "set_action_item_done" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::set_action_item_done(app.state(), request).await)
        }
        "get_meeting_user_notes" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::meeting::get_meeting_user_notes(app.state(), session_id).await)
        }
        "save_meeting_user_notes" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::save_meeting_user_notes(app.state(), request).await)
        }
        "reenhance_meeting_with_notes" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::reenhance_meeting_with_notes(app.state(), request).await)
        }
        "meeting_catch_up" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::meeting::meeting_catch_up(app.state(), session_id).await)
        }
        "meeting_series_template_get" => {
            let mut args = Args::parse(params)?;
            let series_key = args.take("seriesKey")?;
            reply(crate::commands::meeting::meeting_series_template_get(app.state(), series_key).await)
        }
        "meeting_series_template_for_session" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::meeting::meeting_series_template_for_session(app.state(), session_id).await)
        }
        "meeting_series_template_set" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_series_template_set(app.state(), request).await)
        }
        "meeting_series_digest_set" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_series_digest_set(app.state(), request).await)
        }
        "meeting_series_always_record_set" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_series_always_record_set(app.state(), request).await)
        }
        "meeting_series_remote_opt_out_set" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::meeting::meeting_series_remote_opt_out_set(app.state(), request).await)
        }
        "meeting_series_remote_roster" => {
            reply(crate::commands::meeting::meeting_series_remote_roster(app.state()).await)
        }
        "meeting_upcoming_events" => {
            let mut args = Args::parse(params)?;
            let days = args.take("days")?;
            reply(crate::commands::upcoming::meeting_upcoming_events(app.state(), app.state(), days).await)
        }
        "people_list" => {
            reply(crate::commands::people::people_list(app.state()).await)
        }
        "person_detail" => {
            let mut args = Args::parse(params)?;
            let person_id = args.take("personId")?;
            reply(crate::commands::people::person_detail(app.state(), person_id).await)
        }
        "organization_detail" => {
            let mut args = Args::parse(params)?;
            let slug = args.take("slug")?;
            reply(crate::commands::people::organization_detail(app.state(), slug).await)
        }
        "person_summary_regenerate" => {
            let mut args = Args::parse(params)?;
            let person_id = args.take("personId")?;
            reply(crate::commands::people::person_summary_regenerate(app.state(), person_id).await)
        }
        "person_context" => {
            let mut args = Args::parse(params)?;
            let person_ids = args.take("personIds")?;
            reply(crate::commands::people::person_context(app.state(), person_ids).await)
        }
        "meeting_people_context" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::people::meeting_people_context(app.state(), session_id).await)
        }
        "person_rename" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::people::person_rename(app.state(), request).await)
        }
        "person_merge" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::people::person_merge(app.state(), request).await)
        }
        "person_split" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::people::person_split(app.state(), request).await)
        }
        "person_delete" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::people::person_delete(app.state(), request).await)
        }
        "link_confirm" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::people::link_confirm(app.state(), request).await)
        }
        "link_remove" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::people::link_remove(app.state(), request).await)
        }
        "link_add_manual" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::people::link_add_manual(app.state(), request).await)
        }
        "open_loops_inbox" => {
            let mut args = Args::parse(params)?;
            let limit = args.take("limit")?;
            reply(crate::commands::people::open_loops_inbox(app.state(), limit).await)
        }
        "vocabulary_candidates" => {
            reply(crate::commands::people::vocabulary_candidates(app.state()).await)
        }
        "meeting_loops" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::loops::meeting_loops(app.state(), session_id).await)
        }
        "meeting_loop_resolve" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::loops::meeting_loop_resolve(app.state(), request).await)
        }
        "meeting_loop_reopen" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::loops::meeting_loop_reopen(app.state(), request).await)
        }
        "meeting_loop_assign" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::loops::meeting_loop_assign(app.state(), request).await)
        }
        "meeting_follow_up_draft" => {
            let mut args = Args::parse(params)?;
            let operation_id = args.take("operationId")?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::followup::meeting_follow_up_draft(app.state(), operation_id, session_id).await)
        }
        "meeting_follow_up_mail" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::followup::meeting_follow_up_mail(app.state(), request).await)
        }
        "workflows_list" => {
            reply(crate::commands::workflows::workflows_list(app.state()).await)
        }
        "workflow_set_enabled" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::workflows::workflow_set_enabled(app.state(), request).await)
        }
        "workflow_runs" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::workflows::workflow_runs(app.state(), request).await)
        }
        "learning_suggestions" => {
            reply(crate::commands::learning::learning_suggestions(app.state()).await)
        }
        "learning_decide" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::learning::learning_decide(app.clone(), app.state(), request).await)
        }
        "doc_ingest" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::documents::doc_ingest(app.state(), request).await)
        }
        "doc_list" => {
            let mut args = Args::parse(params)?;
            let person_id = args.take("personId")?;
            reply(crate::commands::documents::doc_list(app.state(), person_id).await)
        }
        "doc_delete" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::documents::doc_delete(app.state(), request).await)
        }
        "cloud_sync_overview_get" => {
            reply(crate::commands::cloud_sync::cloud_sync_overview_get(app.state()).await)
        }
        "cloud_sync_meeting_status_get" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::cloud_sync::cloud_sync_meeting_status_get(app.state(), session_id).await)
        }
        "cloud_sync_meeting_status_list" => {
            reply(crate::commands::cloud_sync::cloud_sync_meeting_status_list(app.state()).await)
        }
        "cloud_sync_bootstrap" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::cloud_sync::cloud_sync_bootstrap(app.state(), request).await)
        }
        "cloud_sync_recover" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::cloud_sync::cloud_sync_recover(app.state(), request).await)
        }
        "cloud_sync_pairing_offer" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::cloud_sync::cloud_sync_pairing_offer(app.state(), request).await)
        }
        "cloud_sync_pairing_approve" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::cloud_sync::cloud_sync_pairing_approve(app.state(), request).await)
        }
        "cloud_sync_pairing_fingerprint" => {
            let mut args = Args::parse(params)?;
            let offer = args.take("offer")?;
            on_main_thread(app, move || reply(crate::commands::cloud_sync::cloud_sync_pairing_fingerprint(offer))).await?
        }
        "cloud_sync_pairing_accept" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::cloud_sync::cloud_sync_pairing_accept(app.state(), request).await)
        }
        "cloud_sync_pause" => {
            reply(crate::commands::cloud_sync::cloud_sync_pause(app.state()).await)
        }
        "cloud_sync_resume" => {
            reply(crate::commands::cloud_sync::cloud_sync_resume(app.state()).await)
        }
        "cloud_sync_retry" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::cloud_sync::cloud_sync_retry(app.state(), session_id).await)
        }
        "cloud_sync_conflict_resolve" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::cloud_sync::cloud_sync_conflict_resolve(app.state(), request).await)
        }
        "cloud_share_create" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::cloud_sync::cloud_share_create(app.state(), request).await)
        }
        "cloud_browser_share_create" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::cloud_sync::cloud_browser_share_create(app.state(), request).await)
        }
        "cloud_share_revoke" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::cloud_sync::cloud_share_revoke(app.state(), request).await)
        }
        "cloud_share_import_file" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::cloud_sync::cloud_share_import_file(app.state(), request).await)
        }
        "cloud_sync_service_status" => {
            let handle = app.clone();
            off_main_thread(move || encode_plain(crate::commands::cloud_sync::cloud_sync_service_status(handle.clone(), handle.state()))).await?
        }
        "check_for_updates" => {
            reply(crate::commands::updates::check_for_updates(app.clone()).await)
        }
        "change_update_check_enabled_setting" => {
            let mut args = Args::parse(params)?;
            let enabled = args.take("enabled")?;
            let handle = app.clone();
            on_main_thread(app, move || reply(crate::commands::updates::change_update_check_enabled_setting(handle.clone(), enabled))).await?
        }
        "is_laptop" => {
            on_main_thread(app, move || reply(crate::helpers::clamshell::is_laptop())).await?
        }
        "detection_status_get" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::detection::detection_status_get(handle.state()))).await?
        }
        "detection_calendar_access_request" => {
            reply(crate::commands::detection::detection_calendar_access_request(app.state()).await)
        }
        "detection_notification_access_request" => {
            reply(crate::commands::detection::detection_notification_access_request(app.state()).await)
        }
        "detection_prompt_respond" => {
            let mut args = Args::parse(params)?;
            let prompt_id = args.take("promptId")?;
            let accepted = args.take("accepted")?;
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::detection::detection_prompt_respond(handle.state(), prompt_id, accepted))).await?
        }
        "detection_prompt_panel_ack" => {
            let mut args = Args::parse(params)?;
            let prompt_id = args.take("promptId")?;
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::detection::detection_prompt_panel_ack(handle.state(), prompt_id))).await?
        }
        "meeting_ritual_panel_ack" => {
            let mut args = Args::parse(params)?;
            let ritual_id = args.take("ritualId")?;
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::detection::meeting_ritual_panel_ack(handle.state(), ritual_id))).await?
        }
        "meeting_ritual_respond" => {
            let mut args = Args::parse(params)?;
            let ritual_id = args.take("ritualId")?;
            let action = args.take("action")?;
            reply(crate::commands::detection::meeting_ritual_respond(app.state(), ritual_id, action).await)
        }
        "detection_running_meeting_apps" => {
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::detection::detection_running_meeting_apps(handle.state()))).await?
        }
        "detection_settings_set" => {
            let mut args = Args::parse(params)?;
            let settings = args.take("settings")?;
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::detection::detection_settings_set(handle.state(), settings))).await?
        }
        "sona_query_search" => {
            let mut args = Args::parse(params)?;
            let scope = args.take("scope")?;
            let query = args.take("query")?;
            let limit = args.take("limit")?;
            let cursor = args.take("cursor")?;
            reply(crate::commands::query::sona_query_search(app.state(), app.state(), scope, query, limit, cursor).await)
        }
        "sona_query_events" => {
            let mut args = Args::parse(params)?;
            let after_id = args.take("afterId")?;
            let limit = args.take("limit")?;
            reply(crate::commands::query::sona_query_events(app.state(), after_id, limit).await)
        }
        "sona_query_pack" => {
            let mut args = Args::parse(params)?;
            let question = args.take("question")?;
            reply(crate::commands::query::sona_query_pack(app.state(), app.state(), app.state(), question).await)
        }
        "sona_open_link" => {
            let mut args = Args::parse(params)?;
            let link = args.take("link")?;
            let handle = app.clone();
            on_main_thread(app, move || encode_plain(crate::commands::query::sona_open_link(handle.clone(), link))).await?
        }
        "meeting_series_automations_get" => {
            let mut args = Args::parse(params)?;
            let series_key = args.take("seriesKey")?;
            reply(crate::commands::automations::meeting_series_automations_get(app.state(), series_key).await)
        }
        "meeting_series_automations_for_session" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::automations::meeting_series_automations_for_session(app.state(), session_id).await)
        }
        "meeting_series_automation_set" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::automations::meeting_series_automation_set(app.state(), request).await)
        }
        "meeting_automation_roster" => {
            reply(crate::commands::automations::meeting_automation_roster(app.state()).await)
        }
        "meeting_automation_runs" => {
            let mut args = Args::parse(params)?;
            let session_id = args.take("sessionId")?;
            reply(crate::commands::automations::meeting_automation_runs(app.state(), session_id).await)
        }
        "saved_prompt_list" => {
            reply(crate::commands::prompts::saved_prompt_list(app.state()).await)
        }
        "saved_prompt_save" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::prompts::saved_prompt_save(app.state(), request).await)
        }
        "saved_prompt_delete" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::prompts::saved_prompt_delete(app.state(), request).await)
        }
        "saved_prompt_run" => {
            let mut args = Args::parse(params)?;
            let request = args.take("request")?;
            reply(crate::commands::prompts::saved_prompt_run(app.state(), request).await)
        }
        "saved_prompt_runs" => {
            let mut args = Args::parse(params)?;
            let target = args.take("target")?;
            reply(crate::commands::prompts::saved_prompt_runs(app.state(), target).await)
        }
        other => Err(Fault::unknown_method(other)),
    }
}
